spring:
    application:
        name: reference

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Abcd1234!
        url: jdbc:mysql://3.35.87.115/reference
        username: ref
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false

    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

server:
    port: 8080
    servlet:
        context-path: /ref

jwt:
    issuer: skdlawo5985@gmail.com
    secret: 4XudNUpSmog3lwI9thJFejF7YfBBQnCI

file:
    upload:
        path: uploads/

front:
    url: 'http://localhost:3000'

openai:
    api:
        key: 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